### ISSUE TITLE
adding post to the group giving undefiend error

### ISSUE THREAD

**Issue by SilverAlt** [Vide0Master/pi-archive#15]
{rslt: 's', msg: 'Got post groups of [RevenAlt]', groups: Array(7)}
APIrequest.js:16 
        
        
       POST http://vmtech.hopto.org:2000/api net::ERR_CONNECTION_REFUSED
request @ APIrequest.js:16
(анонимная) @ view_controller.js:343
(анонимная) @ globalPageFunctions.js:372
handleMouseUp_ @ неизвестно
APIrequest.js:37 Ошибка запроса: TypeError: Failed to fetch
    at request (APIrequest.js:16:32)
    at view_controller.js:343:56
    at HTMLSelectElement.<anonymous> (globalPageFunctions.js:372:9)
request @ APIrequest.js:37
await in request
(анонимная) @ view_controller.js:343
(анонимная) @ globalPageFunctions.js:372
handleMouseUp_ @ неизвестно

**Comment by Vide0Master** [comment]
was caused by faulty error check

fixed
