### ISSUE TITLE
Предложение по дизайну

### ISSUE THREAD

**Issue by Toma229** [Vide0Master/pi-archive#18]
Украсть отсюда оценки:
![Screenshot_2024-10-26-17-12-06-703_org telegram messenger](https://github.com/user-attachments/assets/56a023ab-32a1-478e-a074-8c8f50cbd213)

**Comment by Vide0Master** [comment]
done.
![image](https://github.com/user-attachments/assets/a32db5bf-b31b-4739-80f9-4fbbfe3a2757)
![image](https://github.com/user-attachments/assets/e187cb13-5c2e-47e3-acd1-79591185a0df)
![image](https://github.com/user-attachments/assets/d0dc951e-af76-4e8f-a1c2-2e4daeaa8c9b)
